export const COLOR_PRIMARY = "#333333";
export const COLOR_SELECTED = "#EC6B4D";

export enum TKColors {
  ACCENT = "#1B657C",
  BACKGROUND = "#ffffff",
  BACKGROUND_SECONDARY = "#F5F3E8",
  CHART_COLOR_1 = "#6FC5BC",
  CHART_COLOR_2 = "#1B657C",
  CHART_COLOR_3 = "#4595AD",
  CHART_COLOR_4 = "#F1D7AC",
  CHART_COLOR_5 = "#EEEDF7",
  CHART_COLOR_6 = "#CBA0A1",
  CHART_COLOR_7 = "#8C9CB0",
  CHART_COLOR_8 = "#D3E0C9",
  DARK_GREY = "#2C2C2C",
  SECONDARY = "#999999",
  TRAFFICLIGHT_OK = "#BBDFBB",
  TRAFFICLIGHT_WARNING = "#F1BF3C",
  TRAFFICLIGHT_DANGER = "#EC6B4D",
  TRAFFICLIGHT_CRITICAL = "#e30000",
  TRAFFICLIGHT_UNDEFINED = "#1B657C",
  TRAFFICLIGHT_NORESULT = "#e30000",
  TRAFFICLIGHT_PDF_OK = "#87C787",
  TRAFFICLIGHT_PDF_WARNING = "#F1BF3C",
  TRAFFICLIGHT_PDF_DANGER = "#EC6B4D",
  TRAFFICLIGHT_PDF_CRITICAL = "#e30000",
  TRAFFICLIGHT_PDF_UNDEFINED = "#1B657C",
  TRAFFICLIGHT_PDF_NORESULT = "#e30000",
  WHITE = "#ffffff"
}
